name: Deploy
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 최신 코드 땡겨오기
        uses: actions/checkout@main
        with:
          ref: main

      - name: 전역 의존성 설치 및 전역 설정
        run: |
          corepack enable

      - name: 로컬 의존성 설치
        run: |
          yarn

      - name: .env 생성
        run: |
          touch .env
          > .env
          echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} >> .env
          echo AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} >> .env

      - name: 배포 전 확인
        run: |
          cat .env
          yarn why next

      - name: 배포
        run: |
          yarn deploy
